[project]
name = "pingpong-study"
version = "6.8.1"
description = "An app to support the PingPong College RCT study."
readme = "README.md"
requires-python = ">= 3.11, <4.0.0"
authors = [
    { name = "Evangelos Kassos", email = "github@evangeloskassos.com" }
]
license = "MIT"
dependencies = [
    "aiohttp>=3.13.3,<4.0.0",
    "aiosmtplib>=5.1.0,<6.0.0",
    "arrow>=1.4.0,<2.0.0",
    "azure-communication-email>=1.1.0,<2.0.0",
    "click>=8.3.1,<9.0.0",
    "dotenv>=0.9.9,<1.0.0",
    "fastapi[standard]>=0.129.0,<1.0.0",
    "opentelemetry-api>=1.20.0,<2.0.0",
    "opentelemetry-sdk>=1.23.0,<2.0.0",
    "pyairtable>=3.3.0,<4.0.0",
    "pydantic>=2.12.5,<3.0.0",
    "pydantic-settings>=2.12.0,<3.0.0",
    "pyjwt>=2.11.0,<3.0.0",
    "requests>=2.32.5,<3.0.0",
    "sentry-sdk>=2.52.0,<3.0.0",
    "uvicorn>=0.40.0,<1.0.0",
]

[dependency-groups]
dev = [
    "deptry>=0.24.0,<1.0.0",
    "pre-commit>=4.5.0,<5.0.0",
]

local-scripts-qualtrics = [
    "selenium>=4.40.0,<5.0.0",
]

[tool.deptry]
known_first_party = ["pingpong"]
