name: UI â€” Study

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths: [web/study/**]
  pull_request:
    branches: [main]
    paths: [web/study/**]

jobs:
  build-study:
    name: Test Frontend Study
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      wd: ./web/study/
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v5
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: ${{env.wd}}
        run: pnpm install

      - name: Linting
        working-directory: ${{env.wd}}
        run: pnpm lint

      - name: Type checking
        working-directory: ${{env.wd}}
        run: pnpm check

      - name: Check formatting
        working-directory: ${{env.wd}}
        run: |
          pnpm format

          # Verify no code changed
          git diff HEAD --exit-code || {
              echo
              echo -e "\033[91m" 'Looks like you did not check in formatted files :(' "\033[0m"
              echo
              echo -e "\033[91m" 'Run `pnpm format` and check in the result.' "\033[0m"
              exit 1
          }
