name: Python

on:
  push:
    branches: [main]
    paths: [pingpong/**, conftest.py, uv.lock, pyproject.toml, .github/workflows/**]
  pull_request:
    branches: [main]
    paths: [pingpong/**, conftest.py, uv.lock, pyproject.toml, .github/workflows/**]

permissions:
  contents: read

jobs:
  build:
    name: Test Python
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      wd: ./
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b
        with:
          enable-cache: true

      - name: Set up Python3.x
        uses: actions/setup-python@v6
        with:
          python-version: 3.11.6
        id: py

      - name: Get requirements
        working-directory: ${{env.wd}}
        run: |
          uv sync --locked --color never

      - name: Linting, formatting, and type checking
        working-directory: ${{env.wd}}
        run: uv run pre-commit run --show-diff-on-failure --all-files
